#ifndef COMMON_H
#define COMMON_H

#define V4L2_CID_BASE_EXTCTR					0x0A046D01
#define V4L2_CID_BASE_LOGITECH					V4L2_CID_BASE_EXTCTR
//#define V4L2_CID_PAN_RELATIVE_LOGITECH		V4L2_CID_BASE_LOGITECH
//#define V4L2_CID_TILT_RELATIVE_LOGITECH		V4L2_CID_BASE_LOGITECH+1
#define V4L2_CID_PANTILT_RESET_LOGITECH			V4L2_CID_BASE_LOGITECH+2

/*this should realy be replaced by V4L2_CID_FOCUS_ABSOLUTE in libwebcam*/
#define V4L2_CID_FOCUS_LOGITECH					V4L2_CID_BASE_LOGITECH+3


#endif // COMMON_H
